### ISSUE TITLE
Infografía - S1

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-Yabin-2021-1#1]
Aquí se deposita la infografía.

[Infografia - S1 IS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Yabin-2021-1/files/8057959/Infografia.-.S1.IS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 18%

**Comment by josealfredo79** [comment]
Falta agregar lo del estandar

**Comment by josealfredo79** [comment]
Bien hecho y revisado
