### ISSUE TITLE
Practica 1 Interfaces Graficas

### ISSUE THREAD

**Issue by josealfredo79** [SistemasTecTlaxiaco/infografia-Yabin-2021-1#2]
![image](https://user-images.githubusercontent.com/58342642/156188729-753a285f-f9b4-47c2-88a7-1f149e29c9d1.png)
Ejemplo de captura

**Comment by josealfredo79** [comment]
https://docs.google.com/document/d/1-N2s-boONLopXdeE7hA97TYzI6wvymXVrDwCN6hbZXc/edit
Aqui esta la practica 1

**Comment by Yabin-2021** [comment]
[Infografia - S1 IS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Yabin-2021-1/files/8894509/Infografia.-.S1.IS.pdf)

Anexo Infografía.

**Comment by Ferch0419** [comment]
Buen trabajo: 20/20.

**Comment by josealfredo79** [comment]
Bien hehco y revisado...
